version: "3.7"

services:
  fix-mongodb-permissions:
    image: busybox
    user: root
    command: chown -R 1001:1001 /bitnami
    volumes:
      - mongo-vol:/bitnami

  mongodb:
    image: bitnami/mongodb:latest
    restart: on-failure
    environment:
      - MONGODB_PRIMARY_ROOT_USER=root
      - MONGODB_USERNAME=excel-rma
      - MONGODB_PASSWORD=admin
      - MONGODB_DATABASE=excel-rma
      - MONGODB_ROOT_PASSWORD=admin
      - SERVER_DB=rma-server
      - SERVER_USER=rma-server
      - SERVER_DB_PASSWORD=admin
      - CACHE_DB=cache-db
      - CACHE_USER=cache-db
      - CACHE_DB_PASSWORD=admin
    volumes:
      - mongo-vol:/bitnami
    ports:
      - 27017:27017
    depends_on:
      - fix-mongodb-permissions

  mongo-configuration:
    image: bitnami/mongodb:latest
    command:
      - bash
      - -c
      - >
        sleep 10;
        mongo rma-server \
          --host localhost \
          --port 27017 \
          -u root \
          -p admin \
          --authenticationDatabase admin \
          --eval "db.createUser({user: 'rma-server', pwd: 'admin', roles:[{role:'dbOwner', db: 'rma-server'}]});";

        mongo cache-db \
          --host localhost \
          --port 27017 \
          -u root \
          -p admin \
          --authenticationDatabase admin \
          --eval "db.createUser({user: 'cache-db', pwd: 'admin', roles:[{role:'dbOwner', db: 'cache-db'}]});";

  development:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock
      - ..:/workspace
    working_dir: /workspace
    ports:
      - "8800:8800"

volumes:
  mongo-vol:
