/* eslint-disable */
export const CSV_TEMPLATE = {
  delivery_note: `"ID","Series","Customer","Company","Date","Posting Time","Status","Set Source Warehouse","Price List","Price List Exchange Rate","Exchange Rate","Price List Currency","Currency","Item Code (Items)","Item Name (Items)","Description (Items)","Quantity (Items)","Amount (Items)","UOM (Items)","Stock UOM (Items)","UOM Conversion Factor (Items)","Against Sales Invoice (Items)","Serial No (Items)","Rate (Items)"
  `,

  purchase_receipt: `"ID","Series","Supplier","Date","Posting Time","Company","Currency","Exchange Rate","Net Total (Company Currency)","Status","Item Code (Items)","Item Name (Items)","Description (Items)","Received Quantity (Items)","Accepted Quantity (Items)","UOM (Items)","Stock UOM (Items)","Conversion Factor (Items)","Rate (Company Currency) (Items)","Accepted Warehouse (Items)","Rejected Warehouse (Items)","Serial No (Items)","Purchase Order (Items)"
  `,
};

export const CSV_TEMPLATE_HEADERS = {
  purchase_receipt: [
    'naming_series',
    'naming_series',
    'supplier',
    'posting_date',
    'posting_time',
    'company',
    'currency',
    'conversion_rate',
    'total',
    'status',
    ['items', '0', 'item_code'],
    ['items', '0', 'item_name'],
    ['items', '0', 'description'],
    ['items', '0', 'qty'],
    ['items', '0', 'qty'],
    ['items', '0', 'uom'],
    ['items', '0', 'stock_uom'],
    ['items', '0', 'conversion_factor'],
    ['items', '0', 'rate'],
    ['items', '0', 'warehouse'],
    ['items', '0', 'warehouse'],
    ['items', '0', 'serial_no'],
    ['items', '0', 'purchase_order'],
  ],
  delivery_note: [
    'naming_series',
    'naming_series',
    'customer',
    'company',
    'posting_date',
    'posting_time',
    'status',
    'set_warehouse',
    'selling_price_list',
    'plc_conversion_rate',
    'plc_conversion_rate',
    'price_list_currency',
    'price_list_currency',
    ['items', '0', 'item_code'],
    ['items', '0', 'item_name'],
    ['items', '0', 'item_name'],
    ['items', '0', 'qty'],
    ['items', '0', 'amount'],
    ['items', '0', 'uom'],
    ['items', '0', 'stock_uom'],
    ['items', '0', 'conversion_factor'],
    ['items', '0', 'against_sales_invoice'],
    ['items', '0', 'serial_no'],
    ['items', '0', 'rate'],
  ],
};
