export const AGENDA_JOB_METADATA = {
  name: '',
  type: 'single',
  data: null,
  lastModifiedBy: null,
  nextRunAt: new Date(),
  token: null,
  priority: 0,
  inQueue: false,
  repeatInterval: null,
  repeatTimezone: null,
  lockedAt: null,
  lastRunAt: new Date(),
  lastFinishedAt: new Date(),
};
